language: go

go:
  - 1.5.4
  - 1.6.3
  - 1.7rc3
  - tip

env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
    - GO_FOR_RELEASE=1.6.3

services:
  - mongodb

matrix:
  allow_failures:
    - go: tip

script:
  - make test